Add climb code
systemoverloadrobotics/robotcode2020 pull request #14
Opened 2020-02-02 01:30 UTC by yoshiyahoo

ive added some basic code for the climbing system

2020-02-02 03:16 UTC, SOR-FRCTeam6059 submitted a review, later dismissed

2020-02-02 03:16 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
>      public Climb() {
add set to factory default for both your motors

2020-02-02 03:16 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
> +import frc.robot.Constants;
add '.Climb' to the end of this import

2020-02-02 03:16 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
> +        winchMotor.set(0.3);
these are both +

2020-02-02 03:16 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
> +        if(elevatorMotor.isFwdLimitSwitchClosed() != 1){
add tge 1 to the constants file

2020-02-02 03:16 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
> +            elevatorMotor.set(-0.3);
same with these power outputs

2020-02-02 03:16 UTC, Palak-Guleria submitted a review, later dismissed

2020-02-03 06:15 UTC, SOR-FRCTeam6059 requested changes

2020-02-03 06:15 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
> +        winchMotor.set(-0.3);
add these to the constants

2020-02-04 07:02 UTC, SOR-FRCTeam6059 submitted a review, later dismissed

2020-02-04 07:02 UTC, SOR-FRCTeam6059 commented on src/main/java/frc/robot/subsystems/Climb.java
> +        winchMotor.set(-ClimbConstants.WINCH_POWER_CONSTANT);
have this as a seperate constant incase the forward speed needs to be less or more than the backwards

2020-02-06 02:23 UTC, Palak-Guleria approved these changes

2020-02-06 02:24 UTC, Palak-Guleria approved these changes

2020-02-06 02:26 UTC, merged