Double solenoid storage
systemoverloadrobotics/robotcode2020 pull request #28
Opened 2020-02-09 02:22 UTC by yoshiyahoo

2020-02-11 04:05 UTC, MichaelCrandall submitted a review, later dismissed
You commited a change to the .xml file, please remove this commit from your pr

2020-02-11 04:37 UTC, yoshiyahoo commented
I removed the file from the commit

2020-02-11 17:25 UTC, MichaelCrandall requested changes
Master was updated so you need to pull from master to get the most recent code

2020-02-11 17:25 UTC, MichaelCrandall commented on src/main/java/frc/robot/subsystems/Storage.java
> +    private DoubleSolenoid m_doubleSolenoid = new DoubleSolenoid(3,0,1);
all of these should be constants

2020-02-15 19:23 UTC, MichaelCrandall approved these changes

2020-02-15 19:23 UTC, merged