Base driver test
systemoverloadrobotics/robotcode2020 pull request #33
Opened 2020-02-21 02:53 UTC by yoshiyahoo

2020-02-23 02:30 UTC, Palak-Guleria submitted a review, later dismissed

2020-02-25 01:50 UTC, MichaelCrandall commented
You must resolve these conflicts before I can merge your branch

2020-02-29 23:59 UTC, MichaelCrandall requested changes

2020-02-29 23:59 UTC, MichaelCrandall commented on .idea/gradle.xml
>  <?xml version="1.0" encoding="UTF-8"?>
dont change this file

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/Robot.java
>   * project.
dont change this file

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/RobotContainer.java
> +    private final GoToBottom m_goToBottom = new GoToBottom(m_climb); //TODO: The first argument will always be the subsystem
remove this extra tab

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/commands/ExampleCommand.java
> +/*----------------------------------------------------------------------------*/
we dont want this file

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/commands/Park.java
> +package frc.robot.commands;
have this use PIDCommand

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/commands/ShiftUp.java
> +        return false;
this should be true

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/commands/TankDrive.java
> +        double m_leftSpeed = RobotContainer.left_joystick.getY();
make sure this also changed

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/subsystems/Autonomous.java
> +package frc.robot.subsystems;
we do not want this file

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +        double x;
are you sure this is how you get the value from limelimelight, I thought .getDouble() was to choice which pipeline we wanted

2020-02-29 23:59 UTC, MichaelCrandall commented on src/main/java/frc/robot/subsystems/ExampleSubsystem.java
> +/*----------------------------------------------------------------------------*/
we do not want this file

2020-03-01 01:02 UTC, MichaelCrandall approved these changes

2020-03-01 01:03 UTC, merged